version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:14
    depends_on:
      - postgresql
    ports:
      - "5080:8080"

  dest-app:
    image: nginx
    ports:
      - "5081:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./demo/dest-app:/usr/share/nginx/html

  start-app:
    image: nginx
    ports:
      - "5082:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./demo/start-app:/usr/share/nginx/html

volumes:
  postgresql_data:
    driver: local
